/*
Created by codegen
*/
// This file was automatically generated by lister-gen

package v1alpha1

// RedisDBListerExpansion allows custom methods to be added to
// RedisDBLister.
type RedisDBListerExpansion interface{}

// RedisDBNamespaceListerExpansion allows custom methods to be added to
// RedisDBNamespaceLister.
type RedisDBNamespaceListerExpansion interface{}
