/*
Created by codegen
*/
// This file was automatically generated by informer-gen

package v1

import (
	internalinterfaces "github.com/krallistic/redis-operator-demo/pkg/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Redisdbs returns a RedisdbInformer.
	Redisdbs() RedisdbInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// Redisdbs returns a RedisdbInformer.
func (v *version) Redisdbs() RedisdbInformer {
	return &redisdbInformer{factory: v.SharedInformerFactory}
}
