/*
Created by codegen
*/
// This file was automatically generated by lister-gen

package v1

// RedisdbListerExpansion allows custom methods to be added to
// RedisdbLister.
type RedisdbListerExpansion interface{}

// RedisdbNamespaceListerExpansion allows custom methods to be added to
// RedisdbNamespaceLister.
type RedisdbNamespaceListerExpansion interface{}
